name: Data Auto Updater
on:
  push:
    branches:
      - master
  schedule:
    # Run at 5:18 UTC daily 
    - cron:  '18 5 * * *'

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_UPDATER_REPO_ACCESS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data-builder/requirements.txt
      - name: Run script 
        run: |
          python data-builder/build.py --discord ${{ secrets.AUTO_UPDATER_DISCORD_HOOK }}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit latest data
          commit_user_name: Data Auto Updater
          file_pattern: site/src/assets/*.json
          
